name = "FeatureRegistries"
uuid = "c6aefb4f-3ac3-4095-8805-528476b02c02"
authors = ["lorenzoh <lorenz.ohly@gmail.com> and contributors"]
version = "0.1.1"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
InlineTest = "bd334432-b1e7-49c7-a2dc-dd9149e4ebd6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
ImageShow = "0.3"
InlineTest = "0.2"
PrettyTables = "1"
Setfield = "0.8"
StructArrays = "0.6"
julia = "1"

[pollen]
title = "FeatureRegistries.jl"
